# Generated by Django 4.1 on 2022-08-04 21:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pregunta',
            name='creador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Creador de la pregunta'),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='evento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.evento', verbose_name='Evento en el que fue creada'),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='imagen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.imagen', verbose_name='Imagen'),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='tema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.tema', verbose_name='Tema'),
        ),
        migrations.AddField(
            model_name='partida',
            name='preguntas',
            field=models.ManyToManyField(through='base.AnswerLogs', to='base.pregunta'),
        ),
        migrations.AddField(
            model_name='partida',
            name='tema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.tema', verbose_name='Tema'),
        ),
        migrations.AddField(
            model_name='partida',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='opcion',
            name='pregunta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.pregunta', verbose_name='Pregunta'),
        ),
        migrations.AddField(
            model_name='mejoresvaloradas',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.evento', verbose_name='Evento'),
        ),
        migrations.AddField(
            model_name='mejoresvaloradas',
            name='pregunta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.pregunta', verbose_name='Pregunta'),
        ),
        migrations.AddField(
            model_name='mejoresvaloradas',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='imagen',
            name='tema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.tema', verbose_name='Tema'),
        ),
        migrations.AddField(
            model_name='evento',
            name='tema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.tema', verbose_name='Tema'),
        ),
        migrations.AddField(
            model_name='duelos',
            name='partidaUser1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Partida_retador', to='base.partida', verbose_name='Partida del retador'),
        ),
        migrations.AddField(
            model_name='duelos',
            name='partidaUser2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Partida_retado', to='base.partida', verbose_name='Partida del retado'),
        ),
        migrations.AddField(
            model_name='answerlogs',
            name='partida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.partida', verbose_name='Partida'),
        ),
        migrations.AddField(
            model_name='answerlogs',
            name='pregunta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.pregunta', verbose_name='Pregunta'),
        ),
        migrations.AddField(
            model_name='answerlogs',
            name='respuesta_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.opcion', verbose_name='Respuesta del usuario'),
        ),
        migrations.AlterUniqueTogether(
            name='mejoresvaloradas',
            unique_together={('evento', 'usuario', 'pregunta')},
        ),
        migrations.AlterUniqueTogether(
            name='answerlogs',
            unique_together={('partida', 'pregunta')},
        ),
    ]
