# Generated by Django 4.1 on 2022-09-07 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_duelos_created_date_alter_duelos_modified_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partida',
            name='inicio',
        ),
    ]
