# Generated by Django 4.1 on 2022-09-07 20:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0004_remove_partida_inicio'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='answerlogs',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='report',
            name='pregunta',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.pregunta', verbose_name='Pregunta'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='reporter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario que reporta'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='report',
            unique_together={('reporter', 'pregunta')},
        ),
        migrations.RemoveField(
            model_name='report',
            name='log',
        ),
    ]
