# Generated by Django 4.1 on 2022-09-09 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_answerlogs_unique_together_report_pregunta_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partida',
            name='preguntas',
        ),
        migrations.AlterField(
            model_name='answerlogs',
            name='partida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='base.partida', verbose_name='Partida'),
        ),
    ]
