# Generated by Django 4.1 on 2022-09-11 13:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0007_duelos_user1_duelos_user2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answerlogs',
            name='acierto',
        ),
        migrations.RemoveField(
            model_name='partida',
            name='modoJuego',
        ),
        migrations.RemoveField(
            model_name='partida',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='usercomp',
            name='id',
        ),
        migrations.AddField(
            model_name='usercomp',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='participante', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='duelos',
            name='partidaUser1',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Partida_retador', to='base.partida', verbose_name='Partida del retador'),
        ),
        migrations.AlterField(
            model_name='duelos',
            name='partidaUser2',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Partida_retado', to='base.partida', verbose_name='Partida del retado'),
        ),
        migrations.AlterField(
            model_name='usercomp',
            name='partida',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='base.partida', verbose_name='Partida'),
        ),
        migrations.CreateModel(
            name='Repaso',
            fields=[
                ('partida', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='base.partida', verbose_name='Partida')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Repaso',
                'verbose_name_plural': 'Repasos',
            },
        ),
    ]
