# Generated by Django 4.1 on 2022-09-11 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_remove_answerlogs_acierto_remove_partida_modojuego_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partida',
            name='idioma',
            field=models.SmallIntegerField(choices=[(1, 'Esp'), (2, 'Ing')], null=True, verbose_name='Idioma'),
        ),
    ]
