# Generated by Django 4.1 on 2022-09-18 15:34

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0011_alter_pregunta_estado_alter_pregunta_evento'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usercomp',
            unique_together={('evento', 'user')},
        ),
    ]
