# Generated by Django 4.1 on 2022-09-19 16:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0012_alter_usercomp_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercomp',
            name='score_f1',
        ),
        migrations.RemoveField(
            model_name='usercomp',
            name='score_f2',
        ),
        migrations.RemoveField(
            model_name='usercomp',
            name='score_f3',
        ),
        migrations.AddField(
            model_name='report',
            name='evento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.evento', verbose_name='Evento'),
        ),
        migrations.AlterField(
            model_name='duelos',
            name='estado',
            field=models.SmallIntegerField(choices=[(1, 'En Creacion'), (2, 'Pendiente'), (3, 'Finalizada'), (4, 'Rechazada')], default=1, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='evento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pregunta', to='base.evento', verbose_name='Evento en el que fue creada'),
        ),
        migrations.AlterField(
            model_name='report',
            name='reporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que reporta'),
        ),
    ]
