# Generated by Django 4.1 on 2022-09-19 21:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0014_partida_dispositivo_pregunta_dispositivo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partida',
            name='dispositivo',
            field=models.SmallIntegerField(choices=[(1, 'Pc'), (2, 'Movil'), (3, 'Tablet')], default=1, verbose_name='Dispositivo'),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='dispositivo',
            field=models.SmallIntegerField(choices=[(1, 'Pc'), (2, 'Movil'), (3, 'Tablet')], default=1, verbose_name='Dispositivo'),
        ),
        migrations.AlterField(
            model_name='report',
            name='dispositivo',
            field=models.SmallIntegerField(choices=[(1, 'Pc'), (2, 'Movil'), (3, 'Tablet')], default=1, verbose_name='Dispositivo'),
        ),
        migrations.AlterField(
            model_name='report',
            name='pregunta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='base.pregunta', verbose_name='Pregunta'),
        ),
        migrations.AlterField(
            model_name='report',
            name='reporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_reports', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que reporta'),
        ),
    ]
