# Generated by Django 4.1 on 2022-09-20 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_alter_partida_dispositivo_alter_pregunta_dispositivo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answerlogs',
            name='acierto',
            field=models.BooleanField(null=True, verbose_name='Acierto'),
        ),
    ]
