# Generated by Django 4.1 on 2022-09-21 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_answerlogs_acierto'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercomp',
            name='score',
            field=models.IntegerField(null=True, verbose_name='Puntuación'),
        ),
    ]
