# Generated by Django 4.1 on 2022-09-21 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_usercomp_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercomp',
            name='score',
            field=models.PositiveIntegerField(null=True, verbose_name='Puntuación'),
        ),
    ]
