# Generated by Django 4.1 on 2022-10-03 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_alter_usercomp_score'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='opcion',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='duelos',
            name='estado',
            field=models.SmallIntegerField(choices=[(1, 'En Creacion'), (2, 'Pendiente'), (3, 'Finalizado'), (4, 'Rechazado'), (5, 'Aceptado')], default=1, verbose_name='Estado'),
        ),
    ]
