# Generated by Django 4.1 on 2023-03-26 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_alter_opcion_unique_together_alter_duelos_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregunta',
            name='estado',
            field=models.SmallIntegerField(choices=[(1, 'En Evento'), (2, 'Activa'), (3, 'Eliminada'), (4, 'Reportada')], default=1, verbose_name='Estado'),
        ),
    ]
