# Generated by Django 4.1 on 2023-06-18 14:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eventos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.ImageField(unique=True, upload_to='img/', verbose_name='Imagen Pregunta')),
                ('nombre', models.CharField(max_length=30, unique=True, verbose_name='Nombre de la imagen')),
            ],
            options={
                'verbose_name': 'Imagen',
                'verbose_name_plural': 'Imágenes',
            },
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('enunciado', models.CharField(max_length=400, verbose_name='Enunciado')),
                ('estado', models.SmallIntegerField(choices=[(1, 'En Evento'), (2, 'Activa'), (3, 'Eliminada'), (4, 'Reportada')], default=1, verbose_name='Estado')),
                ('idioma', models.SmallIntegerField(choices=[(1, 'Esp'), (2, 'Ing')], default=1, verbose_name='Idioma')),
                ('nValorada', models.IntegerField(default=0, verbose_name='Número de veces valorada')),
                ('valoracionAcumulada', models.IntegerField(default=0, verbose_name='Valoración acumulada')),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Creador de la pregunta')),
                ('evento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pregunta', to='eventos.evento', verbose_name='Evento en el que fue creada')),
                ('imagen', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='preguntas.imagen', verbose_name='Imagen')),
            ],
            options={
                'verbose_name': 'Pregunta',
                'verbose_name_plural': 'Preguntas',
            },
        ),
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, unique=True, verbose_name='Nombre del tema')),
            ],
            options={
                'verbose_name': 'Tema',
                'verbose_name_plural': 'Temas',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('motivo', models.SmallIntegerField(choices=[(1, 'Incorrecto'), (2, 'Ofensivo'), (3, 'Otro Motivo')], verbose_name='Motivo')),
                ('descripcion', models.CharField(max_length=400, verbose_name='Descripción')),
                ('estado', models.SmallIntegerField(choices=[(1, 'Pendiente'), (2, 'Validado'), (3, 'Invalidado')], default=1, verbose_name='Estado')),
                ('evento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='eventos.evento', verbose_name='Evento')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='preguntas.pregunta', verbose_name='Pregunta')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_reports', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que reporta')),
            ],
            options={
                'verbose_name': 'Pregunta reportada',
                'verbose_name_plural': 'Preguntas reportadas',
            },
        ),
        migrations.AddField(
            model_name='pregunta',
            name='tema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='preguntas.tema', verbose_name='Tema'),
        ),
        migrations.CreateModel(
            name='Opcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=400, verbose_name='Texto')),
                ('esCorrecta', models.BooleanField(verbose_name='Es correcta')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opciones', to='preguntas.pregunta', verbose_name='Pregunta')),
            ],
            options={
                'verbose_name': 'Opción',
                'verbose_name_plural': 'Opciones',
            },
        ),
        migrations.AddField(
            model_name='imagen',
            name='tema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='preguntas.tema', verbose_name='Tema'),
        ),
    ]
