# Generated by Django 4.1 on 2023-06-11 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preguntas', '0002_alter_pregunta_id_alter_report_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='report',
            unique_together=set(),
        ),
    ]
