# Generated by Django 4.1 on 2023-05-26 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partidas', '0004_alter_answerlogs_timefin_alter_answerlogs_timeini'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariopregunta',
            name='espaciado',
            field=models.FloatField(default=1, verbose_name='Espaciado'),
        ),
        migrations.AlterField(
            model_name='usuariopregunta',
            name='historico',
            field=models.FloatField(default=0.5, verbose_name='Historico'),
        ),
    ]
