# Generated by Django 4.1 on 2023-05-27 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partidas', '0005_alter_usuariopregunta_espaciado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariopregunta',
            name='espaciado',
            field=models.FloatField(default=0.5, verbose_name='Espaciado'),
        ),
    ]
