# Generated by Django 4.1 on 2023-06-01 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partidas', '0006_alter_usuariopregunta_espaciado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answerlogs',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='duelos',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='partida',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='usuariopregunta',
            name='espaciado',
            field=models.FloatField(default=0, verbose_name='Espaciado'),
        ),
    ]
