# Generated by Django 4.1 on 2023-06-11 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partidas', '0007_alter_answerlogs_id_alter_duelos_id_alter_partida_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answerlogs',
            name='reportada',
            field=models.BooleanField(default=False, verbose_name='Reportada'),
        ),
    ]
