# Generated by Django 4.1 on 2023-06-18 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
                ('fechaInicio', models.DateTimeField(verbose_name='Fecha de inicio del evento')),
                ('finFase1', models.DateTimeField(verbose_name='Fin de la fase de creación de pregunta')),
                ('finFase2', models.DateTimeField(verbose_name='Fin de la fase de cuestionarios')),
                ('idioma', models.SmallIntegerField(choices=[(1, 'Esp'), (2, 'Ing')], default=1, verbose_name='Idioma')),
                ('terminada', models.BooleanField(default=False, verbose_name='Evento terminado')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
            },
        ),
    ]
